Type.create(name: "bug", image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Pok%C3%A9mon_Bug_Type_Icon.svg", pokemon_with_type: 93, moves_with_type: 32, damage_relations_overview_id: 1)
Type.create(name: "dark", image_url: "https://upload.wikimedia.org/wikipedia/commons/0/09/Pok%C3%A9mon_Dark_Type_Icon.svg", pokemon_with_type: 78, moves_with_type: 49, damage_relations_overview_id: 2)
Type.create(name: "dragon", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pok%C3%A9mon_Dragon_Type_Icon.svg", pokemon_with_type: 76, moves_with_type: 27, damage_relations_overview_id: 3)
Type.create(name: "electric", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg", pokemon_with_type: 77, moves_with_type: 45, damage_relations_overview_id: 4)
Type.create(name: "fairy", image_url: "https://upload.wikimedia.org/wikipedia/commons/0/08/Pok%C3%A9mon_Fairy_Type_Icon.svg", pokemon_with_type: 68, moves_with_type: 32, damage_relations_overview_id: 5)
Type.create(name: "fighting", image_url: "https://upload.wikimedia.org/wikipedia/commons/b/be/Pok%C3%A9mon_Fighting_Type_Icon.svg", pokemon_with_type: 80, moves_with_type: 53, damage_relations_overview_id: 6)
Type.create(name: "fire", image_url: "https://upload.wikimedia.org/wikipedia/commons/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg", pokemon_with_type: 87, moves_with_type: 43, damage_relations_overview_id: 7)
Type.create(name: "flying", image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Pok%C3%A9mon_Flying_Type_Icon.svg", pokemon_with_type: 125, moves_with_type: 31, damage_relations_overview_id: 8)
Type.create(name: "ghost", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Pok%C3%A9mon_Ghost_Type_Icon.svg", pokemon_with_type: 75, moves_with_type: 32, damage_relations_overview_id: 9)
Type.create(name: "grass", image_url: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pok%C3%A9mon_Grass_Type_Icon.svg", pokemon_with_type: 125, moves_with_type: 56, damage_relations_overview_id: 10)
Type.create(name: "ground", image_url: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Pok%C3%A9mon_Ground_Type_Icon.svg", pokemon_with_type: 83, moves_with_type: 31, damage_relations_overview_id: 11)
Type.create(name: "ice", image_url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Pok%C3%A9mon_Ice_Type_Icon.svg", pokemon_with_type: 60, moves_with_type: 30, damage_relations_overview_id: 12)
Type.create(name: "normal", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Pok%C3%A9mon_Normal_Type_Icon.svg", pokemon_with_type: 130, moves_with_type: 191, damage_relations_overview_id: 13)
Type.create(name: "poison", image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Pok%C3%A9mon_Poison_Type_Icon.svg", pokemon_with_type: 84, moves_with_type: 33, damage_relations_overview_id: 14)
Type.create(name: "psychic", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Pok%C3%A9mon_Psychic_Type_Icon.svg", pokemon_with_type: 124, moves_with_type: 75, damage_relations_overview_id: 15)
Type.create(name: "rock", image_url: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Pok%C3%A9mon_Rock_Type_Icon.svg", pokemon_with_type: 80, moves_with_type: 24, damage_relations_overview_id: 16)
Type.create(name: "steel", image_url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Pok%C3%A9mon_Steel_Type_Icon.svg", pokemon_with_type: 75, moves_with_type: 34, damage_relations_overview_id: 17)
Type.create(name: "water", image_url: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pok%C3%A9mon_Water_Type_Icon.svg", pokemon_with_type: 159, moves_with_type: 47, damage_relations_overview_id: 18)

DamageRelationsOverview.create(weaknesses: 3, strengths: 3, neutral: 8, resistances: 3)
DamageRelationsOverview.create(weaknesses: 3, strengths: 2, neutral: 13, resistances: 2)
DamageRelationsOverview.create(weaknesses: 3, strengths: 1, neutral: 15, resistances: 4)
DamageRelationsOverview.create(weaknesses: 1, strengths: 2, neutral: 12, resistances: 3)
DamageRelationsOverview.create(weaknesses: 2, strengths: 3, neutral: 12, resistances: 3)
DamageRelationsOverview.create(weaknesses: 3, strengths: 5, neutral: 7, resistances: 3)
DamageRelationsOverview.create(weaknesses: 3, strengths: 4, neutral: 10, resistances: 6)
DamageRelationsOverview.create(weaknesses: 3, strengths: 3, neutral: 12, resistances: 3)
DamageRelationsOverview.create(weaknesses: 2, strengths: 2, neutral: 14, resistances: 2)
DamageRelationsOverview.create(weaknesses: 5, strengths: 3, neutral: 8, resistances: 4)
DamageRelationsOverview.create(weaknesses: 3, strengths: 5, neutral: 10, resistances: 2)
DamageRelationsOverview.create(weaknesses: 4, strengths: 4, neutral: 10, resistances: 1)
DamageRelationsOverview.create(weaknesses: 1, strengths: 0, neutral: 15, resistances: 0)
DamageRelationsOverview.create(weaknesses: 2, strengths: 2, neutral: 11, resistances: 5)
DamageRelationsOverview.create(weaknesses: 3, strengths: 2, neutral: 13, resistances: 2)